/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 326fa47baec5
 */

import { generationGenerateImageFromImages } from "../../funcs/generationGenerateImageFromImages.js";
import { ImageToImageRequest$zodSchema } from "../../models/imagetoimagerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ImageToImageRequest$zodSchema.describe(
    `A JSON object containing the image-to-image generation request parameters.`,
  ),
};

export const tool$generationGenerateImageFromImages: ToolDefinition<
  typeof args
> = {
  name: "generate-image-from-images",
  description: `Generate an image from reference images

Generate an image guided by one or more **reference images** — restyle,
on-brand variants, character consistency, virtual try-on, edit/extend —
steered by \`prompt\`.

Only edit-capable models are selectable here. The model is selected via
the optional \`model\` object, exactly like \`text_to_image\`, but IDs are
restricted to edit models:
1. If \`model.id\` is provided, use that exact edit model.
2. Else if \`model.family\` (+ optional \`model.tier\`) is provided, resolve
   to that family's edit model (e.g. \`nano-banana\` / \`premium\` →
   \`nano-banana-2-edit\`).
3. Else if \`model.mode\` is \`auto\`, the service picks an edit model for
   the request (optionally steered by \`model.preference\`).
4. Otherwise, use the default edit model (\`nano-banana-2-edit\`).

Each reference image is either a stored managed asset (by \`asset_id\`,
read-permission checked) or an external HTTPS \`url\`.
`,
  scopes: ["builder"],
  annotations: {
    "title": "Generate an Image from Reference Images",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await generationGenerateImageFromImages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
