/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 358095938b5f
 */

import * as z from "zod";
import { generationGenerateImage } from "../../funcs/generationGenerateImage.js";
import { GenerateImageRequest$zodSchema } from "../../models/generateimagerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  cloud_name: z.string().describe(
    "The cloud name of your Cloudinary product environment.",
  ),
  GenerateImageRequest: GenerateImageRequest$zodSchema.describe(
    `A JSON object containing the generation request parameters.`,
  ),
};

export const tool$generationGenerateImage: ToolDefinition<typeof args> = {
  name: "generation-generate-image",
  description: `Generate Image

Generate an image from a text prompt using AI models.

The API resolves which model to invoke using a layered override system:
1. If \`explicit_model\` is provided, use that exact model.
2. If \`model_family\` + \`quality_tier\` are provided, look up the model in the Model Matrix.
3. If only \`model_family\` is provided, default to \`quality_tier: "standard"\`.
4. If no model params are provided, use the global default (nano_banana / standard).
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await generationGenerateImage(
      client,
      args.cloud_name,
      args.GenerateImageRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
