/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 358095938b5f
 */

import { generationGenerateImage } from "../../funcs/generationGenerateImage.js";
import { GenerateImageRequest$zodSchema } from "../../models/generateimagerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GenerateImageRequest$zodSchema.describe(
    `A JSON object containing the generation request parameters.`,
  ),
};

export const tool$generationGenerateImage: ToolDefinition<typeof args> = {
  name: "generation-generate-image",
  description: `Generate an image

Generate an image from a text prompt using AI models.

The model is selected via the optional \`model\` object:
1. If \`model.id\` is provided, use that exact model.
2. Else if \`model.family\` (+ optional \`model.tier\`) is provided, resolve via the model registry; a missing tier defaults to \`standard\`.
3. If \`model\` is omitted, use the global default (nano-banana / standard).
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await generationGenerateImage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
