/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d4dcec03e501
 */

import * as z from "zod";
import { tasksGetGenerationTaskStatus } from "../../funcs/tasksGetGenerationTaskStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  cloud_name: z.string().describe(
    "The cloud name of your Cloudinary product environment.",
  ),
  task_id: z.string().describe("The ID of the generation task."),
};

export const tool$tasksGetGenerationTaskStatus: ToolDefinition<typeof args> = {
  name: "tasks-get-generation-task-status",
  description: `Get generation task status

Get the status of a generation task.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetGenerationTaskStatus(
      client,
      args.cloud_name,
      args.task_id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
