/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e523cb9c814
 */

import * as z from "zod";
import { Feature, Feature$zodSchema } from "./feature.js";

/**
 * Quota usage for a single add-on.
 */
export type AddonQuota = {
  type: Feature;
  used_by_request?: number | null | undefined;
  remaining?: number | null | undefined;
  limit?: number | null | undefined;
};

export const AddonQuota$zodSchema: z.ZodType<AddonQuota> = z.object({
  limit: z.int().nullable().optional().describe(
    "Maximum generations allowed per period.",
  ),
  remaining: z.int().nullable().optional().describe(
    "Generations remaining in the current period.",
  ),
  type: Feature$zodSchema.describe("The add-on a quota applies to."),
  used_by_request: z.int().nullable().optional().describe(
    "Number of generations consumed by this request.",
  ),
}).describe("Quota usage for a single add-on.");
