/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0ccb8dd8898a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Output aspect ratio, width-to-height.
 */
export const AspectRatio = {
  Eleven: "1:1",
  ThirtyTwo: "3:2",
  TwentyThree: "2:3",
  FortyThree: "4:3",
  ThirtyFour: "3:4",
  FortyFive: "4:5",
  OneHundredAndSixtyNine: "16:9",
  NineHundredAndSixteen: "9:16",
  OneThousandSixHundredAndTen: "16:10",
  TwoHundredAndNineteen: "21:9",
} as const;
/**
 * Output aspect ratio, width-to-height.
 */
export type AspectRatio = ClosedEnum<typeof AspectRatio>;

export const AspectRatio$zodSchema = z.enum([
  "1:1",
  "3:2",
  "2:3",
  "4:3",
  "3:4",
  "4:5",
  "16:9",
  "9:16",
  "16:10",
  "21:9",
]).describe("Output aspect ratio, width-to-height.");

/**
 * Output resolution tier, measured on the longest edge. Defaults to
 *
 * @remarks
 * `1K` when omitted.
 * * `0.5K`: ~512 px
 * * `1K`: ~1024 px
 * * `2K`: ~2048 px
 * * `4K`: ~4096 px
 */
export const Resolution = {
  ZeroDot5K: "0.5K",
  OneK: "1K",
  TwoK: "2K",
  FourK: "4K",
} as const;
/**
 * Output resolution tier, measured on the longest edge. Defaults to
 *
 * @remarks
 * `1K` when omitted.
 * * `0.5K`: ~512 px
 * * `1K`: ~1024 px
 * * `2K`: ~2048 px
 * * `4K`: ~4096 px
 */
export type Resolution = ClosedEnum<typeof Resolution>;

export const Resolution$zodSchema = z.enum([
  "0.5K",
  "1K",
  "2K",
  "4K",
]).describe(
  "Output resolution tier, measured on the longest edge. Defaults to\n`1K` when omitted.\n* `0.5K`: ~512 px\n* `1K`: ~1024 px\n* `2K`: ~2048 px\n* `4K`: ~4096 px\n",
);

/**
 * Declarative output size — an aspect ratio plus an optional resolution
 *
 * @remarks
 * tier, resolved server-side to the nearest size the model supports.
 */
export type DeclarativeImageSize = {
  aspect_ratio: AspectRatio;
  resolution?: Resolution | undefined;
};

export const DeclarativeImageSize$zodSchema: z.ZodType<DeclarativeImageSize> = z
  .object({
    aspect_ratio: AspectRatio$zodSchema.describe(
      "Output aspect ratio, width-to-height.",
    ),
    resolution: Resolution$zodSchema.optional().describe(
      "Output resolution tier, measured on the longest edge. Defaults to\n`1K` when omitted.\n* `0.5K`: ~512 px\n* `1K`: ~1024 px\n* `2K`: ~2048 px\n* `4K`: ~4096 px\n",
    ),
  }).describe(
    "Declarative output size — an aspect ratio plus an optional resolution\ntier, resolved server-side to the nearest size the model supports.\n",
  );
