/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ce5e680288e9
 */

import * as z from "zod";

/**
 * Exact output dimensions in pixels. Both `width` and `height` are required together.
 */
export type DimensionsImageSize = { width: number; height: number };

export const DimensionsImageSize$zodSchema: z.ZodType<DimensionsImageSize> = z
  .object({
    height: z.int().describe("Output height in pixels."),
    width: z.int().describe("Output width in pixels."),
  }).describe(
    "Exact output dimensions in pixels. Both `width` and `height` are required together.",
  );
