/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55a21b891851
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

/**
 * Wrapper for error responses; includes the error object and a request_id for correlation.
 */
export type ErrorResponse = { error: ErrorT; request_id: string };

export const ErrorResponse$zodSchema: z.ZodType<ErrorResponse> = z.object({
  error: ErrorT$zodSchema.describe(
    "Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.",
  ),
  request_id: z.string(),
}).describe(
  "Wrapper for error responses; includes the error object and a request_id for correlation.",
);
