/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 369096a8494a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Coarse classification of an error, primarily used by clients to decide whether to retry.
 */
export const ErrorCategory = {
  UserError: "user_error",
  AuthError: "auth_error",
  ServerError: "server_error",
  RateLimitError: "rate_limit_error",
} as const;
/**
 * Coarse classification of an error, primarily used by clients to decide whether to retry.
 */
export type ErrorCategory = ClosedEnum<typeof ErrorCategory>;

export const ErrorCategory$zodSchema = z.enum([
  "user_error",
  "auth_error",
  "server_error",
  "rate_limit_error",
]).describe(
  "Coarse classification of an error, primarily used by clients to decide whether to retry.",
);
