/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55a21b891851
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";

/**
 * Wrapper for error responses. The shape of `error` is the same across status codes.
 */
export type ErrorResponse = { error?: ErrorObject | null | undefined };

export const ErrorResponse$zodSchema: z.ZodType<ErrorResponse> = z.object({
  error: ErrorObject$zodSchema.nullable().optional().describe(
    "Details of an error. Always carries a category, a stable code, and a human-readable message.",
  ),
}).describe(
  "Wrapper for error responses. The shape of `error` is the same across status codes.",
);
