/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 369096a8494a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Coarse classification of an error, primarily used by clients to decide whether to retry.
 *
 * @remarks
 * * `user_error`: the request was invalid; do not retry without changes.
 * * `auth_error`: authentication or authorization failed.
 * * `server_error`: an unexpected server-side error; retrying may succeed.
 * * `rate_limit_error`: quota or rate limit exceeded; retry later.
 */
export const ErrorCategory = {
  UserError: "user_error",
  AuthError: "auth_error",
  ServerError: "server_error",
  RateLimitError: "rate_limit_error",
} as const;
/**
 * Coarse classification of an error, primarily used by clients to decide whether to retry.
 *
 * @remarks
 * * `user_error`: the request was invalid; do not retry without changes.
 * * `auth_error`: authentication or authorization failed.
 * * `server_error`: an unexpected server-side error; retrying may succeed.
 * * `rate_limit_error`: quota or rate limit exceeded; retry later.
 */
export type ErrorCategory = ClosedEnum<typeof ErrorCategory>;

export const ErrorCategory$zodSchema = z.enum([
  "user_error",
  "auth_error",
  "server_error",
  "rate_limit_error",
]).describe(
  "Coarse classification of an error, primarily used by clients to decide whether to retry.\n* `user_error`: the request was invalid; do not retry without changes.\n* `auth_error`: authentication or authorization failed.\n* `server_error`: an unexpected server-side error; retrying may succeed.\n* `rate_limit_error`: quota or rate limit exceeded; retry later.\n",
);
