/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d53a586acbe6
 */

import * as z from "zod";
import { ErrorCategory, ErrorCategory$zodSchema } from "./errorcategory.js";

export type Details = {};

export const Details$zodSchema: z.ZodType<Details> = z.object({});

/**
 * Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.
 */
export type ErrorT = {
  category?: ErrorCategory | undefined;
  code?: string | undefined;
  message?: string | undefined;
  details?: Details | undefined;
};

export const ErrorT$zodSchema: z.ZodType<ErrorT> = z.object({
  category: ErrorCategory$zodSchema.optional().describe(
    "Coarse classification of an error, primarily used by clients to decide whether to retry.",
  ),
  code: z.string().optional(),
  details: z.lazy(() => Details$zodSchema).optional(),
  message: z.string().optional(),
}).describe(
  "Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.",
);
