/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 31d7acca0a1e
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The add-on a quota applies to.
 */
export const Feature = {
  ImageGeneration: "image_generation",
} as const;
/**
 * The add-on a quota applies to.
 */
export type Feature = ClosedEnum<typeof Feature>;

export const Feature$zodSchema = z.enum([
  "image_generation",
]).describe("The add-on a quota applies to.");
