/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4931b83a9fa
 */

import * as z from "zod";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GenerateImageRequest,
  GenerateImageRequest$zodSchema,
} from "./generateimagerequest.js";
import {
  GenerateImageResponse,
  GenerateImageResponse$zodSchema,
} from "./generateimageresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type GenerateImageRequestRequest = {
  cloud_name: string;
  GenerateImageRequest: GenerateImageRequest;
};

export const GenerateImageRequestRequest$zodSchema: z.ZodType<
  GenerateImageRequestRequest
> = z.object({
  GenerateImageRequest: GenerateImageRequest$zodSchema.describe(
    "A JSON object containing the generation request parameters.",
  ),
  cloud_name: z.string().describe(
    "The cloud name of your Cloudinary product environment.",
  ),
});

export type GenerateImageResponseResponse =
  | GenerateImageResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const GenerateImageResponseResponse$zodSchema: z.ZodType<
  GenerateImageResponseResponse
> = z.union([
  GenerateImageResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
