/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 612a8e835a58
 */

import * as z from "zod";
import {
  GeneratedImageData,
  GeneratedImageData$zodSchema,
} from "./generatedimagedata.js";

/**
 * Wrapper holding the array of generated assets. Always an array even
 *
 * @remarks
 * though `n` is currently capped at 1 — reserves the multi-output shape.
 */
export type GeneratedAssets = { assets: Array<GeneratedImageData> };

export const GeneratedAssets$zodSchema: z.ZodType<GeneratedAssets> = z.object({
  assets: z.array(GeneratedImageData$zodSchema).describe(
    "The generated assets. One element today (n capped at 1).",
  ),
}).describe(
  "Wrapper holding the array of generated assets. Always an array even\nthough `n` is currently capped at 1 — reserves the multi-output shape.\n",
);
