/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 612a8e835a58
 */

import * as z from "zod";
import { GeneratedAsset, GeneratedAsset$zodSchema } from "./generatedasset.js";

/**
 * Wrapper holding the array of generated assets.
 */
export type GeneratedAssets = { assets: Array<GeneratedAsset> };

export const GeneratedAssets$zodSchema: z.ZodType<GeneratedAssets> = z.object({
  assets: z.array(GeneratedAsset$zodSchema).describe(
    "The generated assets. Currently a single asset is returned.",
  ),
}).describe("Wrapper holding the array of generated assets.");
