/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4931b83a9fa
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GenerateImageResult,
  GenerateImageResult$zodSchema,
} from "./generateimageresult.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";
import { TaskResponse, TaskResponse$zodSchema } from "./taskresponse.js";

export type GenerateImageGlobals = { cloud_name?: string | undefined };

export const GenerateImageGlobals$zodSchema: z.ZodType<GenerateImageGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type GenerateImageResponse =
  | ErrorResponse
  | RateLimitedResponse
  | GenerateImageResult
  | TaskResponse;

export const GenerateImageResponse$zodSchema: z.ZodType<GenerateImageResponse> =
  z.union([
    ErrorResponse$zodSchema,
    RateLimitedResponse$zodSchema,
    GenerateImageResult$zodSchema,
    TaskResponse$zodSchema,
  ]);
