/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4931b83a9fa
 */

import * as z from "zod";
import {
  AsyncOperationAcceptedResponse,
  AsyncOperationAcceptedResponse$zodSchema,
} from "./asyncoperationacceptedresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GenerateImageResponse,
  GenerateImageResponse$zodSchema,
} from "./generateimageresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";

export type GenerateImageGlobals = { cloud_name?: string | undefined };

export const GenerateImageGlobals$zodSchema: z.ZodType<GenerateImageGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type GenerateImageResponseResponse =
  | GenerateImageResponse
  | AsyncOperationAcceptedResponse
  | ErrorResponse
  | RateLimitedResponse;

export const GenerateImageResponseResponse$zodSchema: z.ZodType<
  GenerateImageResponseResponse
> = z.union([
  GenerateImageResponse$zodSchema,
  AsyncOperationAcceptedResponse$zodSchema,
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
]);
