/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d57bdb4cae78
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ModelInfo, ModelInfo$zodSchema } from "./modelinfo.js";

/**
 * The image format of the stored asset.
 */
export const Format = {
  Png: "png",
  Jpg: "jpg",
  Webp: "webp",
} as const;
/**
 * The image format of the stored asset.
 */
export type Format = ClosedEnum<typeof Format>;

export const Format$zodSchema = z.enum([
  "png",
  "jpg",
  "webp",
]).describe("The image format of the stored asset.");

/**
 * The generated image, its metadata, and the model that produced it.
 */
export type GeneratedImageData = {
  secure_url: string;
  format: Format;
  width: number;
  height: number;
  bytes: number;
  model: ModelInfo;
  seed?: number | null | undefined;
  created_at: string;
};

export const GeneratedImageData$zodSchema: z.ZodType<GeneratedImageData> = z
  .object({
    bytes: z.int().describe("The size of the generated image in bytes."),
    created_at: z.iso.datetime({ offset: true }).describe(
      "The timestamp when the image was generated.",
    ),
    format: Format$zodSchema.describe("The image format of the stored asset."),
    height: z.int().describe(
      "The height of the generated image in pixels. Zero when the model doesn't return dimensions.",
    ),
    model: ModelInfo$zodSchema.describe(
      "Identifies the model that produced a generation result.",
    ),
    secure_url: z.string().describe("The secure URL for the generated image."),
    seed: z.int().nullable().optional().describe(
      "The seed used for generation. Echoes input or returns the model-generated seed.\nNull when the model doesn't support seeds.\n",
    ),
    width: z.int().describe(
      "The width of the generated image in pixels. Zero when the model doesn't return dimensions.",
    ),
  }).describe(
    "The generated image, its metadata, and the model that produced it.",
  );
