/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 958825c984f2
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Selects the model family:
 *
 * @remarks
 * * `flux` — Photorealistic (FLUX.2 Klein 9B / FLUX.2 Pro).
 * * `recraft` — Vector / Illustration (Recraft V3 / Recraft V4).
 * * `gpt_image` — Campaign / Marketing (GPT Image 1 Mini / GPT Image 2).
 * * `nano_banana` — Fast Draft (Nano Banana / Nano Banana 2).
 */
export const ModelFamily = {
  Flux: "flux",
  Recraft: "recraft",
  GptImage: "gpt_image",
  NanoBanana: "nano_banana",
} as const;
/**
 * Selects the model family:
 *
 * @remarks
 * * `flux` — Photorealistic (FLUX.2 Klein 9B / FLUX.2 Pro).
 * * `recraft` — Vector / Illustration (Recraft V3 / Recraft V4).
 * * `gpt_image` — Campaign / Marketing (GPT Image 1 Mini / GPT Image 2).
 * * `nano_banana` — Fast Draft (Nano Banana / Nano Banana 2).
 */
export type ModelFamily = ClosedEnum<typeof ModelFamily>;

export const ModelFamily$zodSchema = z.enum([
  "flux",
  "recraft",
  "gpt_image",
  "nano_banana",
]).describe(
  "Selects the model family:\n* `flux` — Photorealistic (FLUX.2 Klein 9B / FLUX.2 Pro).\n* `recraft` — Vector / Illustration (Recraft V3 / Recraft V4).\n* `gpt_image` — Campaign / Marketing (GPT Image 1 Mini / GPT Image 2).\n* `nano_banana` — Fast Draft (Nano Banana / Nano Banana 2).\n",
);

/**
 * Selects a model variant within the family:
 *
 * @remarks
 * * `standard` — Faster and cheaper.
 * * `premium` — Higher quality.
 */
export const QualityTier = {
  Standard: "standard",
  Premium: "premium",
} as const;
/**
 * Selects a model variant within the family:
 *
 * @remarks
 * * `standard` — Faster and cheaper.
 * * `premium` — Higher quality.
 */
export type QualityTier = ClosedEnum<typeof QualityTier>;

export const QualityTier$zodSchema = z.enum([
  "standard",
  "premium",
]).describe(
  "Selects a model variant within the family:\n* `standard` — Faster and cheaper.\n* `premium` — Higher quality.\n",
);

/**
 * Overrides model_family + quality_tier with a specific model identifier.
 *
 * @remarks
 * When provided, model_family and quality_tier are ignored.
 * Omit the field entirely (rather than sending null) to fall back to family/tier resolution.
 */
export const ExplicitModel = {
  NanoBanana: "nano-banana",
  NanoBanana2: "nano-banana-2",
  Flux2Klein9b: "flux-2-klein-9b",
  Flux2Pro: "flux-2-pro",
  RecraftV3: "recraft-v3",
  RecraftV4: "recraft-v4",
  GptImage1Mini: "gpt-image-1-mini",
  GptImage2: "gpt-image-2",
} as const;
/**
 * Overrides model_family + quality_tier with a specific model identifier.
 *
 * @remarks
 * When provided, model_family and quality_tier are ignored.
 * Omit the field entirely (rather than sending null) to fall back to family/tier resolution.
 */
export type ExplicitModel = ClosedEnum<typeof ExplicitModel>;

export const ExplicitModel$zodSchema = z.enum([
  "nano-banana",
  "nano-banana-2",
  "flux-2-klein-9b",
  "flux-2-pro",
  "recraft-v3",
  "recraft-v4",
  "gpt-image-1-mini",
  "gpt-image-2",
]).describe(
  "Overrides model_family + quality_tier with a specific model identifier.\nWhen provided, model_family and quality_tier are ignored.\nOmit the field entirely (rather than sending null) to fall back to family/tier resolution.\n",
);

/**
 * Parameters for an image-generation request. Only `prompt` is required;
 *
 * @remarks
 * all other fields fall back to documented defaults.
 */
export type GenerateImageRequest = {
  prompt: string;
  model_family?: ModelFamily | undefined;
  quality_tier?: QualityTier | undefined;
  explicit_model?: ExplicitModel | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  seed?: number | null | undefined;
  async?: boolean | undefined;
  notification_url?: string | undefined;
};

export const GenerateImageRequest$zodSchema: z.ZodType<GenerateImageRequest> = z
  .object({
    async: z.boolean().default(false).describe(
      "Whether to perform the generation asynchronously.\nIf set to true, the API returns immediately and the generation is done in the background.\nOnce generation is complete, a webhook notification is sent to the specified URL and/or to the URLs defined in the cloud's settings.\n",
    ),
    explicit_model: ExplicitModel$zodSchema.optional().describe(
      "Overrides model_family + quality_tier with a specific model identifier.\nWhen provided, model_family and quality_tier are ignored.\nOmit the field entirely (rather than sending null) to fall back to family/tier resolution.\n",
    ),
    height: z.int().nullable().optional().describe(
      "Desired image height in pixels. Passed through to the underlying model.",
    ),
    model_family: ModelFamily$zodSchema.default("nano_banana").describe(
      "Selects the model family:\n* `flux` — Photorealistic (FLUX.2 Klein 9B / FLUX.2 Pro).\n* `recraft` — Vector / Illustration (Recraft V3 / Recraft V4).\n* `gpt_image` — Campaign / Marketing (GPT Image 1 Mini / GPT Image 2).\n* `nano_banana` — Fast Draft (Nano Banana / Nano Banana 2).\n",
    ),
    notification_url: z.string().optional().describe(
      "The webhook URL to notify when the generation is complete. Only relevant when `async` is set to true.",
    ),
    prompt: z.string().describe(
      "The text description of the image to generate.",
    ),
    quality_tier: QualityTier$zodSchema.default("standard").describe(
      "Selects a model variant within the family:\n* `standard` — Faster and cheaper.\n* `premium` — Higher quality.\n",
    ),
    seed: z.int().nullable().optional().describe(
      "Seed for reproducible generation. Supported by most models.\nSilently ignored by models that don't support it.\n",
    ),
    width: z.int().nullable().optional().describe(
      "Desired image width in pixels. Passed through to the underlying model.",
    ),
  }).describe(
    "Parameters for an image-generation request. Only `prompt` is required;\nall other fields fall back to documented defaults.\n",
  );
