/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: caa21e7ab7ee
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GenerateImageResult,
  GenerateImageResult$zodSchema,
} from "./generateimageresult.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";
import { TaskResponse, TaskResponse$zodSchema } from "./taskresponse.js";

export type GenerateImageFromImagesGlobals = {
  cloud_name?: string | undefined;
};

export const GenerateImageFromImagesGlobals$zodSchema: z.ZodType<
  GenerateImageFromImagesGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GenerateImageFromImagesResponse =
  | ErrorResponse
  | RateLimitedResponse
  | GenerateImageResult
  | TaskResponse;

export const GenerateImageFromImagesResponse$zodSchema: z.ZodType<
  GenerateImageFromImagesResponse
> = z.union([
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
  GenerateImageResult$zodSchema,
  TaskResponse$zodSchema,
]);
