/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: de0aa67fae25
 */

import * as z from "zod";
import {
  GeneratedAssets,
  GeneratedAssets$zodSchema,
} from "./generatedassets.js";
import { Limits, Limits$zodSchema } from "./limits.js";

/**
 * Successful synchronous image-generation response.
 */
export type GenerateImageResult = {
  data?: GeneratedAssets | undefined;
  limits?: Limits | undefined;
  request_id: string;
};

export const GenerateImageResult$zodSchema: z.ZodType<GenerateImageResult> = z
  .object({
    data: GeneratedAssets$zodSchema.optional().describe(
      "Wrapper holding the array of generated assets.",
    ),
    limits: Limits$zodSchema.optional().describe(
      "Rate limit information for the account's add-on quotas.",
    ),
    request_id: z.string(),
  }).describe("Successful synchronous image-generation response.");
