/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7ab3867a37e5
 */

import * as z from "zod";
import {
  GeneratedAssets,
  GeneratedAssets$zodSchema,
} from "./generatedassets.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

/**
 * Successful synchronous image-generation response.
 */
export type GenerateImageResponse = {
  limits?: LimitsObject | null | undefined;
  data?: GeneratedAssets | undefined;
  request_id?: string | undefined;
};

export const GenerateImageResponse$zodSchema: z.ZodType<GenerateImageResponse> =
  z.object({
    data: GeneratedAssets$zodSchema.optional().describe(
      "Wrapper holding the array of generated assets. Always an array even\nthough `n` is currently capped at 1 — reserves the multi-output shape.\n",
    ),
    limits: LimitsObject$zodSchema.nullable().optional().describe(
      "Rate limit information for the account's generation quota.",
    ),
    request_id: z.string().optional(),
  }).describe("Successful synchronous image-generation response.");
