/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97a338105c2a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Model, Model$zodSchema } from "./model.js";
import { Storage, Storage$zodSchema } from "./storage.js";

/**
 * The image format of the stored asset.
 */
export const GeneratedAssetFormat = {
  Png: "png",
  Jpg: "jpg",
  Webp: "webp",
} as const;
/**
 * The image format of the stored asset.
 */
export type GeneratedAssetFormat = ClosedEnum<typeof GeneratedAssetFormat>;

export const GeneratedAssetFormat$zodSchema = z.enum([
  "png",
  "jpg",
  "webp",
]).describe("The image format of the stored asset.");

/**
 * A generated asset: where it is stored (`storage`) plus its media
 *
 * @remarks
 * metadata. The media fields are populated once the task completes; an
 * in-progress asset carries only `storage`.
 */
export type GeneratedAsset = {
  storage: Storage;
  format?: GeneratedAssetFormat | undefined;
  width?: number | undefined;
  height?: number | undefined;
  bytes?: number | undefined;
  model?: Model | undefined;
  seed?: number | null | undefined;
  created_at?: string | undefined;
};

export const GeneratedAsset$zodSchema: z.ZodType<GeneratedAsset> = z.object({
  bytes: z.int().optional().describe(
    "The size of the generated image in bytes.",
  ),
  created_at: z.iso.datetime({ offset: true }).optional().describe(
    "The timestamp when the image was generated.",
  ),
  format: GeneratedAssetFormat$zodSchema.optional().describe(
    "The image format of the stored asset.",
  ),
  height: z.int().optional().describe(
    "The height of the generated image in pixels; zero if the model doesn't provide dimensions.",
  ),
  model: Model$zodSchema.optional().describe(
    "Identifies the model that produced a generation result.",
  ),
  seed: z.int().nullable().optional().describe(
    "The seed used for generation. Echoes input or returns the model-generated seed.\nNull when the model doesn't support seeds.\n",
  ),
  storage: Storage$zodSchema.describe(
    "Where a generated asset is stored — mirrors the request `target`,\ndetermined by `storage_type`. `secure_url` is always present.\n",
  ),
  width: z.int().optional().describe(
    "The width of the generated image in pixels; zero if the model doesn't provide dimensions.",
  ),
}).describe(
  "A generated asset: where it is stored (`storage`) plus its media\nmetadata. The media fields are populated once the task completes; an\nin-progress asset carries only `storage`.\n",
);
