/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9a160012644e
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  RateLimitedResponse,
  RateLimitedResponse$zodSchema,
} from "./ratelimitedresponse.js";
import { TaskResponse, TaskResponse$zodSchema } from "./taskresponse.js";

export type GetGenerationTaskStatusGlobals = {
  cloud_name?: string | undefined;
};

export const GetGenerationTaskStatusGlobals$zodSchema: z.ZodType<
  GetGenerationTaskStatusGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetGenerationTaskStatusSecurity = { basicAuth: string };

export const GetGenerationTaskStatusSecurity$zodSchema: z.ZodType<
  GetGenerationTaskStatusSecurity
> = z.object({
  basicAuth: z.string().describe("API Key"),
});

export type GetGenerationTaskStatusRequest = { task_id: string };

export const GetGenerationTaskStatusRequest$zodSchema: z.ZodType<
  GetGenerationTaskStatusRequest
> = z.object({
  task_id: z.string().describe("The ID of the generation task."),
});

export type GetGenerationTaskStatusResponse =
  | ErrorResponse
  | RateLimitedResponse
  | TaskResponse;

export const GetGenerationTaskStatusResponse$zodSchema: z.ZodType<
  GetGenerationTaskStatusResponse
> = z.union([
  ErrorResponse$zodSchema,
  RateLimitedResponse$zodSchema,
  TaskResponse$zodSchema,
]);
