/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b564d8b72b9a
 */

import * as z from "zod";
import {
  GeneratedImageData,
  GeneratedImageData$zodSchema,
} from "./generatedimagedata.js";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";

/**
 * The generated assets. Only present when status is 'completed'.
 */
export type Result = { assets: Array<GeneratedImageData> };

export const Result$zodSchema: z.ZodType<Result> = z.object({
  assets: z.array(GeneratedImageData$zodSchema).describe(
    "The generated assets. One element today (n capped at 1).",
  ),
}).describe("The generated assets. Only present when status is 'completed'.");

export type GetTaskStatusResponseData = {
  task_id?: string | undefined;
  status: TaskStatus;
  result?: Result | null | undefined;
};

export const GetTaskStatusResponseData$zodSchema: z.ZodType<
  GetTaskStatusResponseData
> = z.object({
  result: z.lazy(() => Result$zodSchema).nullable().optional().describe(
    "The generated assets. Only present when status is 'completed'.",
  ),
  status: TaskStatus$zodSchema.describe("The status of an async task."),
  task_id: z.string().optional(),
});

/**
 * Response payload for GET /tasks/{task_id} — current status plus the result once available.
 */
export type GetTaskStatusResponse = {
  data?: GetTaskStatusResponseData | undefined;
  request_id?: string | undefined;
};

export const GetTaskStatusResponse$zodSchema: z.ZodType<GetTaskStatusResponse> =
  z.object({
    data: z.lazy(() => GetTaskStatusResponseData$zodSchema).optional(),
    request_id: z.string().optional(),
  }).describe(
    "Response payload for GET /tasks/{task_id} — current status plus the result once available.",
  );
