/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0e2c2c2f2316
 */

import * as z from "zod";
import {
  DeclarativeImageSize,
  DeclarativeImageSize$zodSchema,
} from "./declarativeimagesize.js";
import {
  DimensionsImageSize,
  DimensionsImageSize$zodSchema,
} from "./dimensionsimagesize.js";

/**
 * Desired output size, given in **one** of two mutually exclusive forms:
 *
 * @remarks
 *
 *   * `DimensionsImageSize`: `width` and `height` in pixels, for precise
 *     control.
 *   * `DeclarativeImageSize`: `aspect_ratio` (and an optional `resolution`
 *     tier), resolved server-side to the closest size the chosen model
 *     supports. This is the portable form: most providers natively accept
 *     an aspect ratio plus a resolution tier rather than raw pixels.
 *
 * Omit `image_size` entirely to use the model's default size.
 */
export type ImageSize = DimensionsImageSize | DeclarativeImageSize;

export const ImageSize$zodSchema: z.ZodType<ImageSize> = z.union([
  DimensionsImageSize$zodSchema,
  DeclarativeImageSize$zodSchema,
]).describe(
  "Desired output size, given in **one** of two mutually exclusive forms:\n\n  * `DimensionsImageSize`: `width` and `height` in pixels, for precise\n    control.\n  * `DeclarativeImageSize`: `aspect_ratio` (and an optional `resolution`\n    tier), resolved server-side to the closest size the chosen model\n    supports. This is the portable form: most providers natively accept\n    an aspect ratio plus a resolution tier rather than raw pixels.\n\nOmit `image_size` entirely to use the model's default size.\n",
);
