/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b163b9ac3a1c
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Desired output image format. Optional; defaults to `png` when omitted.
 *
 * @remarks
 * Mapped to the closest format the chosen model supports — `webp` falls
 * back to `png` on models that don't support it (e.g. FLUX.2 Pro), and the
 * request is ignored entirely by models that don't expose a format option
 * (e.g. Recraft).
 */
export const ImageFormat = {
  Jpeg: "jpeg",
  Png: "png",
  Webp: "webp",
} as const;
/**
 * Desired output image format. Optional; defaults to `png` when omitted.
 *
 * @remarks
 * Mapped to the closest format the chosen model supports — `webp` falls
 * back to `png` on models that don't support it (e.g. FLUX.2 Pro), and the
 * request is ignored entirely by models that don't expose a format option
 * (e.g. Recraft).
 */
export type ImageFormat = ClosedEnum<typeof ImageFormat>;

export const ImageFormat$zodSchema = z.enum([
  "jpeg",
  "png",
  "webp",
]).describe(
  "Desired output image format. Optional; defaults to `png` when omitted.\nMapped to the closest format the chosen model supports — `webp` falls\nback to `png` on models that don't support it (e.g. FLUX.2 Pro), and the\nrequest is ignored entirely by models that don't expose a format option\n(e.g. Recraft).\n",
);
