/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eb60dcc8c8ce
 */

import * as z from "zod";
import { AddonQuota, AddonQuota$zodSchema } from "./addonquota.js";

/**
 * Rate limit information for the account's add-on quotas.
 */
export type Limits = { addons_quota?: Array<AddonQuota> | undefined };

export const Limits$zodSchema: z.ZodType<Limits> = z.object({
  addons_quota: z.array(AddonQuota$zodSchema).optional().describe(
    "Per-add-on quota usage for this account.",
  ),
}).describe("Rate limit information for the account's add-on quotas.");
