/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2401b1ad1b38
 */

import * as z from "zod";
import { QuotaType, QuotaType$zodSchema } from "./quotatype.js";

/**
 * Rate limit information for the account's generation quota.
 */
export type LimitsObject = {
  type: QuotaType;
  used_by_request?: number | null | undefined;
  remaining: number;
  limit: number;
  reset_time: string;
};

export const LimitsObject$zodSchema: z.ZodType<LimitsObject> = z.object({
  limit: z.int().describe("Maximum generations allowed per period."),
  remaining: z.int().describe("Generations remaining in the current period."),
  reset_time: z.iso.datetime({ offset: true }).describe(
    "Time in UTC when the limit will be reset.",
  ),
  type: QuotaType$zodSchema.describe("The type of quota."),
  used_by_request: z.int().nullable().optional().describe(
    "Number of generations consumed by this request.",
  ),
}).describe("Rate limit information for the account's generation quota.");
