/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fc6cfda12670
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Discriminator identifying this as a managed-asset reference.
 */
export const ManagedAssetReferenceSourceType = {
  ManagedAsset: "managed_asset",
} as const;
/**
 * Discriminator identifying this as a managed-asset reference.
 */
export type ManagedAssetReferenceSourceType = ClosedEnum<
  typeof ManagedAssetReferenceSourceType
>;

export const ManagedAssetReferenceSourceType$zodSchema = z.enum([
  "managed_asset",
]).describe("Discriminator identifying this as a managed-asset reference.");

/**
 * A reference to a managed asset in the caller's product environment, by
 *
 * @remarks
 * asset ID.
 */
export type ManagedAssetReference = {
  source_type: ManagedAssetReferenceSourceType;
  asset_id: string;
};

export const ManagedAssetReference$zodSchema: z.ZodType<ManagedAssetReference> =
  z.object({
    asset_id: z.string().describe(
      "Cloudinary asset ID of the reference image. READ permission is enforced.",
    ),
    source_type: ManagedAssetReferenceSourceType$zodSchema.describe(
      "Discriminator identifying this as a managed-asset reference.",
    ),
  }).describe(
    "A reference to a managed asset in the caller's product environment, by\nasset ID.\n",
  );
