/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6fd55dfd5f37
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ManagedAssetStorageStorageType = {
  ManagedAsset: "managed_asset",
} as const;
export type ManagedAssetStorageStorageType = ClosedEnum<
  typeof ManagedAssetStorageStorageType
>;

export const ManagedAssetStorageStorageType$zodSchema = z.enum([
  "managed_asset",
]);

/**
 * Cloudinary resource type of the stored asset.
 */
export const ResourceType = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * Cloudinary resource type of the stored asset.
 */
export type ResourceType = ClosedEnum<typeof ResourceType>;

export const ResourceType$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe("Cloudinary resource type of the stored asset.");

/**
 * A generated asset stored as a permanent managed asset. Reference it in
 *
 * @remarks
 * other Cloudinary APIs by `asset_id`, or by the
 * `resource_type` / `type` / `public_id` triple.
 */
export type ManagedAssetStorage = {
  storage_type: ManagedAssetStorageStorageType;
  secure_url: string;
  asset_id?: string | undefined;
  public_id: string;
  resource_type: ResourceType;
  type: string;
  version: number;
};

export const ManagedAssetStorage$zodSchema: z.ZodType<ManagedAssetStorage> = z
  .object({
    asset_id: z.string().optional().describe(
      "Cloudinary asset ID — a stable, globally-unique reference to the asset.",
    ),
    public_id: z.string().describe("Public ID of the stored asset."),
    resource_type: ResourceType$zodSchema.describe(
      "Cloudinary resource type of the stored asset.",
    ),
    secure_url: z.string().describe("The URL to fetch the generated asset."),
    storage_type: ManagedAssetStorageStorageType$zodSchema,
    type: z.string().describe(
      "Cloudinary delivery type of the stored asset (e.g. `upload`, `private`, `authenticated`).",
    ),
    version: z.int().describe("Version of the stored asset."),
  }).describe(
    "A generated asset stored as a permanent managed asset. Reference it in\nother Cloudinary APIs by `asset_id`, or by the\n`resource_type` / `type` / `public_id` triple.\n",
  );
