/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55f0cd308347
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Exact model identifier; overrides family/tier when provided.
 */
export const Id = {
  NanoBanana1: "nano-banana-1",
  NanoBanana2: "nano-banana-2",
  Flux2Klein9b: "flux-2-klein-9b",
  Flux2Pro: "flux-2-pro",
  RecraftV3: "recraft-v3",
  RecraftV4: "recraft-v4",
  GptImage1Mini: "gpt-image-1-mini",
  GptImage2: "gpt-image-2",
  IdeogramV4Base: "ideogram-v4-base",
  IdeogramV4Turbo: "ideogram-v4-turbo",
} as const;
/**
 * Exact model identifier; overrides family/tier when provided.
 */
export type Id = ClosedEnum<typeof Id>;

export const Id$zodSchema = z.enum([
  "nano-banana-1",
  "nano-banana-2",
  "flux-2-klein-9b",
  "flux-2-pro",
  "recraft-v3",
  "recraft-v4",
  "gpt-image-1-mini",
  "gpt-image-2",
  "ideogram-v4-base",
  "ideogram-v4-turbo",
]).describe("Exact model identifier; overrides family/tier when provided.");

/**
 * Pin an exact model by ID, bypassing family/tier.
 */
export type ModelById = { id: Id };

export const ModelById$zodSchema: z.ZodType<ModelById> = z.object({
  id: Id$zodSchema.describe(
    "Exact model identifier; overrides family/tier when provided.",
  ),
}).describe("Pin an exact model by ID, bypassing family/tier.");
