/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b99d4c14e794
 */

import * as z from "zod";

/**
 * Identifies the model that produced a generation result.
 */
export type Model = { family: string; tier: string; id: string };

export const Model$zodSchema: z.ZodType<Model> = z.object({
  family: z.string().describe("The model family used."),
  id: z.string().describe("The exact model identifier used for generation."),
  tier: z.string().describe("The quality tier used."),
}).describe("Identifies the model that produced a generation result.");
