/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6af9ea6fe52b
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Model family:
 *
 * @remarks
 * * `flux`: Photorealistic images (FLUX.2 Klein 9B / FLUX.2 Pro).
 * * `recraft`: Vector and illustration (Recraft V3 / Recraft V4).
 * * `gpt-image`: Campaign and marketing images (GPT Image 1 Mini / GPT Image 2).
 * * `nano-banana`: General purpose generation (Nano Banana 1 / Nano Banana 2).
 * * `ideogram`: Realism, text rendering, and artistic generation (Ideogram V4).
 */
export const Family = {
  Flux: "flux",
  Recraft: "recraft",
  GptImage: "gpt-image",
  NanoBanana: "nano-banana",
  Ideogram: "ideogram",
} as const;
/**
 * Model family:
 *
 * @remarks
 * * `flux`: Photorealistic images (FLUX.2 Klein 9B / FLUX.2 Pro).
 * * `recraft`: Vector and illustration (Recraft V3 / Recraft V4).
 * * `gpt-image`: Campaign and marketing images (GPT Image 1 Mini / GPT Image 2).
 * * `nano-banana`: General purpose generation (Nano Banana 1 / Nano Banana 2).
 * * `ideogram`: Realism, text rendering, and artistic generation (Ideogram V4).
 */
export type Family = ClosedEnum<typeof Family>;

export const Family$zodSchema = z.enum([
  "flux",
  "recraft",
  "gpt-image",
  "nano-banana",
  "ideogram",
]).describe(
  "Model family:\n* `flux`: Photorealistic images (FLUX.2 Klein 9B / FLUX.2 Pro).\n* `recraft`: Vector and illustration (Recraft V3 / Recraft V4).\n* `gpt-image`: Campaign and marketing images (GPT Image 1 Mini / GPT Image 2).\n* `nano-banana`: General purpose generation (Nano Banana 1 / Nano Banana 2).\n* `ideogram`: Realism, text rendering, and artistic generation (Ideogram V4).\n",
);

/**
 * Quality tier within the family. Defaults to `standard` when omitted.
 */
export const Tier = {
  Standard: "standard",
  Premium: "premium",
} as const;
/**
 * Quality tier within the family. Defaults to `standard` when omitted.
 */
export type Tier = ClosedEnum<typeof Tier>;

export const Tier$zodSchema = z.enum([
  "standard",
  "premium",
]).describe(
  "Quality tier within the family. Defaults to `standard` when omitted.",
);

/**
 * Select a model by family and quality tier; a missing `tier` defaults to
 *
 * @remarks
 * `standard`.
 */
export type ModelByFamily = { family: Family; tier?: Tier | undefined };

export const ModelByFamily$zodSchema: z.ZodType<ModelByFamily> = z.object({
  family: Family$zodSchema.describe(
    "Model family:\n* `flux`: Photorealistic images (FLUX.2 Klein 9B / FLUX.2 Pro).\n* `recraft`: Vector and illustration (Recraft V3 / Recraft V4).\n* `gpt-image`: Campaign and marketing images (GPT Image 1 Mini / GPT Image 2).\n* `nano-banana`: General purpose generation (Nano Banana 1 / Nano Banana 2).\n* `ideogram`: Realism, text rendering, and artistic generation (Ideogram V4).\n",
  ),
  tier: Tier$zodSchema.optional().describe(
    "Quality tier within the family. Defaults to `standard` when omitted.",
  ),
}).describe(
  "Select a model by family and quality tier; a missing `tier` defaults to\n`standard`.\n",
);
