/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d524c67e7c3
 */

import * as z from "zod";

/**
 * Identifies the model that produced a generation result.
 */
export type ModelInfo = { family: string; tier: string; model_id: string };

export const ModelInfo$zodSchema: z.ZodType<ModelInfo> = z.object({
  family: z.string().describe("The model family used."),
  model_id: z.string().describe(
    "The actual model identifier used for generation.",
  ),
  tier: z.string().describe("The quality tier used."),
}).describe("Identifies the model that produced a generation result.");
