/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b549af31aae
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The only valid value; selects automatic model selection.
 */
export const Mode = {
  Auto: "auto",
} as const;
/**
 * The only valid value; selects automatic model selection.
 */
export type Mode = ClosedEnum<typeof Mode>;

export const Mode$zodSchema = z.enum([
  "auto",
]).describe("The only valid value; selects automatic model selection.");

/**
 * What the choice optimizes for:
 *
 * @remarks
 * * `balanced` (default): quality and cost weighted equally.
 * * `quality`: quality only; cost isn't weighed.
 * * `economy`: cost first, quality second.
 * * `balanced_fast`, `quality_fast`, `economy_fast`: as above, but also
 *   favor faster generation, and never pick a model that typically
 *   takes longer than 30 seconds.
 */
export const Preference = {
  Balanced: "balanced",
  Quality: "quality",
  Economy: "economy",
  BalancedFast: "balanced_fast",
  QualityFast: "quality_fast",
  EconomyFast: "economy_fast",
} as const;
/**
 * What the choice optimizes for:
 *
 * @remarks
 * * `balanced` (default): quality and cost weighted equally.
 * * `quality`: quality only; cost isn't weighed.
 * * `economy`: cost first, quality second.
 * * `balanced_fast`, `quality_fast`, `economy_fast`: as above, but also
 *   favor faster generation, and never pick a model that typically
 *   takes longer than 30 seconds.
 */
export type Preference = ClosedEnum<typeof Preference>;

export const Preference$zodSchema = z.enum([
  "balanced",
  "quality",
  "economy",
  "balanced_fast",
  "quality_fast",
  "economy_fast",
]).describe(
  "What the choice optimizes for:\n* `balanced` (default): quality and cost weighted equally.\n* `quality`: quality only; cost isn't weighed.\n* `economy`: cost first, quality second.\n* `balanced_fast`, `quality_fast`, `economy_fast`: as above, but also\n  favor faster generation, and never pick a model that typically\n  takes longer than 30 seconds.\n",
);

/**
 * Let the service choose the model for this request. The response reports
 *
 * @remarks
 * the resolved model in `data.assets[].model`, as for the other forms; on
 * `image_to_image` it is always an edit model.
 */
export type ModelAuto = { mode: Mode; preference?: Preference | undefined };

export const ModelAuto$zodSchema: z.ZodType<ModelAuto> = z.object({
  mode: Mode$zodSchema.describe(
    "The only valid value; selects automatic model selection.",
  ),
  preference: Preference$zodSchema.default("balanced").describe(
    "What the choice optimizes for:\n* `balanced` (default): quality and cost weighted equally.\n* `quality`: quality only; cost isn't weighed.\n* `economy`: cost first, quality second.\n* `balanced_fast`, `quality_fast`, `economy_fast`: as above, but also\n  favor faster generation, and never pick a model that typically\n  takes longer than 30 seconds.\n",
  ),
}).describe(
  "Let the service choose the model for this request. The response reports\nthe resolved model in `data.assets[].model`, as for the other forms; on\n`image_to_image` it is always an edit model.\n",
);
