/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f330319b981c
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * How much weight to give the message.
 *
 * @remarks
 * * `info`: for awareness; nothing to do.
 * * `warning`: worth relaying to the user before continuing.
 * * `blocking`: the request was not served; the text says what unblocks it.
 */
export const Severity = {
  Info: "info",
  Warning: "warning",
  Blocking: "blocking",
} as const;
/**
 * How much weight to give the message.
 *
 * @remarks
 * * `info`: for awareness; nothing to do.
 * * `warning`: worth relaying to the user before continuing.
 * * `blocking`: the request was not served; the text says what unblocks it.
 */
export type Severity = ClosedEnum<typeof Severity>;

export const Severity$zodSchema = z.enum([
  "info",
  "warning",
  "blocking",
]).describe(
  "How much weight to give the message.\n* `info`: for awareness; nothing to do.\n* `warning`: worth relaying to the user before continuing.\n* `blocking`: the request was not served; the text says what unblocks it.\n",
);

export type Notice = { severity: Severity; text: string };

export const Notice$zodSchema: z.ZodType<Notice> = z.object({
  severity: Severity$zodSchema.describe(
    "How much weight to give the message.\n* `info`: for awareness; nothing to do.\n* `warning`: worth relaying to the user before continuing.\n* `blocking`: the request was not served; the text says what unblocks it.\n",
  ),
  text: z.string().describe(
    "The tip or guidance, in plain text. Show it as-is or follow it; the wording may change between releases.",
  ),
});
