/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a6f81c7df116
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of quota.
 */
export const QuotaType = {
  ImageGeneration: "image_generation",
} as const;
/**
 * The type of quota.
 */
export type QuotaType = ClosedEnum<typeof QuotaType>;

export const QuotaType$zodSchema = z.enum([
  "image_generation",
]).describe("The type of quota.");
