/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d632a065f0ef
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Limits, Limits$zodSchema } from "./limits.js";

/**
 * Rate limited.
 */
export type RateLimitedResponse = {
  error: ErrorT;
  limits?: Limits | undefined;
  request_id: string;
};

export const RateLimitedResponse$zodSchema: z.ZodType<RateLimitedResponse> = z
  .object({
    error: ErrorT$zodSchema.describe(
      "Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.",
    ),
    limits: Limits$zodSchema.optional().describe(
      "Rate limit information for the account's add-on quotas.",
    ),
    request_id: z.string(),
  }).describe("Rate limited.");
