/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d632a065f0ef
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Limits, Limits$zodSchema } from "./limits.js";
import { Notice, Notice$zodSchema } from "./notice.js";

/**
 * Rate limited.
 */
export type RateLimitedResponse = {
  error: ErrorT;
  limits?: Limits | undefined;
  notices?: Array<Notice> | undefined;
  request_id: string;
};

export const RateLimitedResponse$zodSchema: z.ZodType<RateLimitedResponse> = z
  .object({
    error: ErrorT$zodSchema.describe(
      "Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.",
    ),
    limits: Limits$zodSchema.optional().describe(
      "Rate limit information for the account's add-on quotas.",
    ),
    notices: z.array(Notice$zodSchema).optional().describe(
      "Tips and guidance attached to the response to help you get the most\nout of the generation. Each entry is plain text you can show to a\nuser or act on as-is. Omitted when there is nothing to add.\n",
    ),
    request_id: z.string().describe(
      "Unique identifier for this request, for correlation and support.",
    ),
  }).describe("Rate limited.");
