/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d632a065f0ef
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LimitsObject, LimitsObject$zodSchema } from "./limitsobject.js";

/**
 * Wrapper for rate-limit metadata. Present on successful generations and on 429 responses.
 */
export type RateLimitedResponse = {
  error?: ErrorObject | null | undefined;
  limits?: LimitsObject | null | undefined;
};

export const RateLimitedResponse$zodSchema: z.ZodType<RateLimitedResponse> = z
  .object({
    error: ErrorObject$zodSchema.nullable().optional().describe(
      "Details of an error. Always carries a category, a stable code, and a human-readable message.",
    ),
    limits: LimitsObject$zodSchema.nullable().optional().describe(
      "Rate limit information for the account's generation quota.",
    ),
  }).describe(
    "Wrapper for rate-limit metadata. Present on successful generations and on 429 responses.",
  );
