/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 25cf64688b41
 */

import * as z from "zod";
import {
  ManagedAssetReference,
  ManagedAssetReference$zodSchema,
} from "./managedassetreference.js";
import { UrlReference, UrlReference$zodSchema } from "./urlreference.js";

/**
 * A single reference image, in **one** of two mutually exclusive forms
 *
 * @remarks
 * determined by `source_type`:
 *   * `ManagedAssetReference`: a managed asset in the caller's product
 *     environment, by `asset_id` (read permission is checked).
 *   * `UrlReference`: an external image by HTTPS `url`.
 */
export type ReferenceImage =
  | (ManagedAssetReference & { source_type: "managed_asset" })
  | (UrlReference & { source_type: "url" });

export const ReferenceImage$zodSchema: z.ZodType<ReferenceImage> = z.union([
  ManagedAssetReference$zodSchema.and(
    z.object({
      source_type: z.literal("managed_asset"),
    }).transform((v) => ({ source_type: v.source_type })),
  ),
  UrlReference$zodSchema.and(
    z.object({
      source_type: z.literal("url"),
    }).transform((v) => ({ source_type: v.source_type })),
  ),
]).describe(
  "A single reference image, in **one** of two mutually exclusive forms\ndetermined by `source_type`:\n  * `ManagedAssetReference`: a managed asset in the caller's product\n    environment, by `asset_id` (read permission is checked).\n  * `UrlReference`: an external image by HTTPS `url`.\n",
);
