/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod";

export type Security = { username: string; password: string };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  password: z.string().describe(
    "Basic authentication using Cloudinary API Key and API Secret. password",
  ),
  username: z.string().describe(
    "Basic authentication using Cloudinary API Key and API Secret. username",
  ),
});
