/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod";

export type Security = { api_key: string; api_secret: string };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  api_key: z.string(),
  api_secret: z.string(),
});
