/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8b534f43f59e
 */

import * as z from "zod";
import {
  ManagedAssetStorage,
  ManagedAssetStorage$zodSchema,
} from "./managedassetstorage.js";
import {
  TemporaryStorage,
  TemporaryStorage$zodSchema,
} from "./temporarystorage.js";

/**
 * Where a generated asset is stored — mirrors the request `target`,
 *
 * @remarks
 * determined by `storage_type`. `secure_url` is always present.
 */
export type Storage =
  | (ManagedAssetStorage & { storage_type: "managed_asset" })
  | (TemporaryStorage & { storage_type: "temporary" });

export const Storage$zodSchema: z.ZodType<Storage> = z.union([
  ManagedAssetStorage$zodSchema.and(
    z.object({
      storage_type: z.literal("managed_asset"),
    }).transform((v) => ({ storage_type: v.storage_type })),
  ),
  TemporaryStorage$zodSchema.and(
    z.object({
      storage_type: z.literal("temporary"),
    }).transform((v) => ({ storage_type: v.storage_type })),
  ),
]).describe(
  "Where a generated asset is stored — mirrors the request `target`,\ndetermined by `storage_type`. `secure_url` is always present.\n",
);
