/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f37077ef7c9a
 */

import * as z from "zod";
import {
  ManagedAssetTarget,
  ManagedAssetTarget$zodSchema,
} from "./managedassettarget.js";
import {
  TemporaryTarget,
  TemporaryTarget$zodSchema,
} from "./temporarytarget.js";

/**
 * Where to store the generated output, determined by `target_type`.
 *
 * @remarks
 * Optional; defaults to a `temporary` target when omitted.
 */
export type Target =
  | (ManagedAssetTarget & { target_type: "managed_asset" })
  | (TemporaryTarget & { target_type: "temporary" });

export const Target$zodSchema: z.ZodType<Target> = z.union([
  ManagedAssetTarget$zodSchema.and(
    z.object({
      target_type: z.literal("managed_asset"),
    }).transform((v) => ({ target_type: v.target_type })),
  ),
  TemporaryTarget$zodSchema.and(
    z.object({
      target_type: z.literal("temporary"),
    }).transform((v) => ({ target_type: v.target_type })),
  ),
]).describe(
  "Where to store the generated output, determined by `target_type`.\nOptional; defaults to a `temporary` target when omitted.\n",
);
