/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 53ca97329a8b
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of an async generation task.
 *
 * @remarks
 * * `pending`: accepted and queued, not yet started.
 * * `processing`: generation is in progress.
 * * `completed`: generation finished; `result` is populated.
 * * `failed`: generation did not complete successfully.
 */
export const TaskStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * The status of an async generation task.
 *
 * @remarks
 * * `pending`: accepted and queued, not yet started.
 * * `processing`: generation is in progress.
 * * `completed`: generation finished; `result` is populated.
 * * `failed`: generation did not complete successfully.
 */
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

export const TaskStatus$zodSchema = z.enum([
  "pending",
  "processing",
  "completed",
  "failed",
]).describe(
  "The status of an async generation task.\n* `pending`: accepted and queued, not yet started.\n* `processing`: generation is in progress.\n* `completed`: generation finished; `result` is populated.\n* `failed`: generation did not complete successfully.\n",
);
