/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9609f5f4adcb
 */

import * as z from "zod";
import { GeneratedAsset, GeneratedAsset$zodSchema } from "./generatedasset.js";
import { Limits, Limits$zodSchema } from "./limits.js";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";

/**
 * The generated assets. Populated once `status` is `completed`.
 *
 * @remarks
 */
export type Result = { assets: Array<GeneratedAsset> };

export const Result$zodSchema: z.ZodType<Result> = z.object({
  assets: z.array(GeneratedAsset$zodSchema).describe(
    "The generated assets. Currently a single asset is returned.",
  ),
}).describe("The generated assets. Populated once `status` is `completed`.\n");

/**
 * An async generation task. Returned when a generation is accepted (202)
 *
 * @remarks
 * and from GET /tasks/{task_id} as it progresses. The `result` is filled
 * in once `status` is `completed`.
 */
export type Task = {
  task_id: string;
  status: TaskStatus;
  result?: Result | null | undefined;
  limits?: Limits | undefined;
};

export const Task$zodSchema: z.ZodType<Task> = z.object({
  limits: Limits$zodSchema.optional().describe(
    "Rate limit information for the account's add-on quotas.",
  ),
  result: z.lazy(() => Result$zodSchema).nullable().optional().describe(
    "The generated assets. Populated once `status` is `completed`.\n",
  ),
  status: TaskStatus$zodSchema.describe("The status of an async task."),
  task_id: z.string(),
}).describe(
  "An async generation task. Returned when a generation is accepted (202)\nand from GET /tasks/{task_id} as it progresses. The `result` is filled\nin once `status` is `completed`.\n",
);
