/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b5ae8dfddaea
 */

import * as z from "zod";
import { Task, Task$zodSchema } from "./task.js";

/**
 * Envelope for an async generation task — returned by the accepted (202)
 *
 * @remarks
 * response and by GET /tasks/{task_id}.
 */
export type TaskResponse = { data?: Task | undefined; request_id: string };

export const TaskResponse$zodSchema: z.ZodType<TaskResponse> = z.object({
  data: Task$zodSchema.optional().describe(
    "An async generation task. Returned when a generation is accepted (202)\nand from GET /tasks/{task_id} as it progresses. The `result` is filled\nin once `status` is `completed`.\n",
  ),
  request_id: z.string(),
}).describe(
  "Envelope for an async generation task — returned by the accepted (202)\nresponse and by GET /tasks/{task_id}.\n",
);
