/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 53ca97329a8b
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of an async task.
 */
export const TaskStatus = {
  Pending: "pending",
  Processing: "processing",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * The status of an async task.
 */
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

export const TaskStatus$zodSchema = z.enum([
  "pending",
  "processing",
  "completed",
  "failed",
]).describe("The status of an async task.");
