/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3585fffc94ea
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TemporaryTargetTargetType = {
  Temporary: "temporary",
} as const;
export type TemporaryTargetTargetType = ClosedEnum<
  typeof TemporaryTargetTargetType
>;

export const TemporaryTargetTargetType$zodSchema = z.enum([
  "temporary",
]);

/**
 * Store the output as a short-lived asset on the upload service (the default).
 */
export type TemporaryTarget = { target_type: TemporaryTargetTargetType };

export const TemporaryTarget$zodSchema: z.ZodType<TemporaryTarget> = z.object({
  target_type: TemporaryTargetTargetType$zodSchema,
}).describe(
  "Store the output as a short-lived asset on the upload service (the default).",
);
