/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: edef5e745a76
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Discriminator identifying this as temporary storage.
 */
export const TemporaryStorageStorageType = {
  Temporary: "temporary",
} as const;
/**
 * Discriminator identifying this as temporary storage.
 */
export type TemporaryStorageStorageType = ClosedEnum<
  typeof TemporaryStorageStorageType
>;

export const TemporaryStorageStorageType$zodSchema = z.enum([
  "temporary",
]).describe("Discriminator identifying this as temporary storage.");

/**
 * A generated asset stored as a short-lived asset on the upload service.
 */
export type TemporaryStorage = {
  storage_type: TemporaryStorageStorageType;
  secure_url: string;
  expires_at: string;
};

export const TemporaryStorage$zodSchema: z.ZodType<TemporaryStorage> = z.object(
  {
    expires_at: z.iso.datetime({ offset: true }).describe(
      "Time in UTC when secure_url stops being valid.",
    ),
    secure_url: z.string().describe("The URL to fetch the generated asset."),
    storage_type: TemporaryStorageStorageType$zodSchema.describe(
      "Discriminator identifying this as temporary storage.",
    ),
  },
).describe(
  "A generated asset stored as a short-lived asset on the upload service.",
);
