/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 84ab494b1c55
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Discriminator identifying this as an external-URL reference.
 */
export const UrlReferenceSourceType = {
  Url: "url",
} as const;
/**
 * Discriminator identifying this as an external-URL reference.
 */
export type UrlReferenceSourceType = ClosedEnum<typeof UrlReferenceSourceType>;

export const UrlReferenceSourceType$zodSchema = z.enum([
  "url",
]).describe("Discriminator identifying this as an external-URL reference.");

/**
 * A reference to an external image by HTTPS URL.
 */
export type UrlReference = { source_type: UrlReferenceSourceType; url: string };

export const UrlReference$zodSchema: z.ZodType<UrlReference> = z.object({
  source_type: UrlReferenceSourceType$zodSchema.describe(
    "Discriminator identifying this as an external-URL reference.",
  ),
  url: z.string().describe("HTTPS URL of the reference image."),
}).describe("A reference to an external image by HTTPS URL.");
